%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\bsteiger\Documents\Personal\dev\monopoly-deal-data\Monopoly Deal Data.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/09/28 13:59:57
function MonopolyDealData = importMonopolyDealData()
%% Initialize variables.
filename = '.\Monopoly Deal Data.csv';
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: categorical (%C)
%	column2: categorical (%C)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%C%C%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
MonopolyDealData = table(dataArray{1:end-1}, 'VariableNames', {'WentFirst','Winner'});

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;